# from https://github.com/nlohmann/json
language: cpp

sudo: false

os:
  - osx

compiler:
  - g++
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./avro_test
